package com.projectronin.interop.fhir.ronin.generators.resource.observation

import com.projectronin.interop.fhir.generators.datatypes.codeableConcept
import com.projectronin.interop.fhir.generators.datatypes.coding
import com.projectronin.interop.fhir.generators.primitives.of
import com.projectronin.interop.fhir.generators.resources.ObservationGenerator
import com.projectronin.interop.fhir.r4.resource.Observation
import com.projectronin.interop.fhir.r4.resource.Patient
import com.projectronin.interop.fhir.ronin.generators.resource.referenceData
import com.projectronin.interop.fhir.ronin.generators.util.generateCodeableConcept
import com.projectronin.interop.fhir.ronin.generators.util.generateEffectiveDateTime
import com.projectronin.interop.fhir.ronin.generators.util.generateReference
import com.projectronin.interop.fhir.ronin.generators.util.rcdmMeta
import com.projectronin.interop.rcdm.common.enums.RoninProfile
import com.projectronin.interop.rcdm.common.metadata.ValueSetMetadata
import com.projectronin.interop.rcdm.registry.model.ValueSetList

/**
 * Helps generate ronin body temperature observation profile, applies meta and randomly generates an
 * acceptable code from the [possibleBodyTemperatureCodes] list, category is generated by base-vital-signs
 */
fun rcdmObservationBodyTemperature(
    tenant: String,
    block: ObservationGenerator.() -> Unit,
): Observation {
    return rcdmBaseObservation(tenant) {
        block.invoke(this)
        meta of rcdmMeta(RoninProfile.OBSERVATION_BODY_TEMPERATURE, tenant) {}
        category of listOf(codeableConcept { coding of vitalSignsCategory })
        code of generateCodeableConcept(code.generate(), possibleBodyTemperatureCodes.codes.random())
        subject of generateReference(subject.generate(), subjectReferenceOptions, tenant, "Patient")
        effective of generateEffectiveDateTime(effective.generate(), possibleDateTime)
    }
}

fun Patient.rcdmObservationBodyTemperature(block: ObservationGenerator.() -> Unit): Observation {
    val data = this.referenceData()
    return rcdmObservationBodyTemperature(data.tenantId) {
        block.invoke(this)
        subject of
            generateReference(
                subject.generate(),
                subjectReferenceOptions,
                data.tenantId,
                "Patient",
                data.udpId,
            )
    }
}

val possibleBodyTemperatureCodes =
    ValueSetList(
        listOf(
            Pair("8310-5", "Body temperature"),
            Pair("8331-1", "Oral temperature"),
            Pair("76011-6", "Ear temperature"),
            Pair("11289-6", "Body temperature at First encounter"),
            Pair("8333-7", "Tympanic membrane temperature"),
            Pair("75539-7", "Body temperature - Temporal artery"),
        ).map {
            coding {
                system of loinc
                version of "2.74"
                code of it.first
                display of it.second
            }
        },
        ValueSetMetadata(
            registryEntryType = "value_set",
            valueSetName = "bodytemperaturenoninvasive",
            valueSetUuid = "798f075e-a48d-49d2-8ace-66aff6f55478",
            version = "2",
        ),
    )
