package com.projectronin.interop.fhir.ronin.generators.resource.observation

import com.projectronin.interop.fhir.generators.datatypes.codeableConcept
import com.projectronin.interop.fhir.generators.datatypes.coding
import com.projectronin.interop.fhir.generators.primitives.of
import com.projectronin.interop.fhir.generators.resources.ObservationGenerator
import com.projectronin.interop.fhir.r4.resource.Observation
import com.projectronin.interop.fhir.r4.resource.Patient
import com.projectronin.interop.fhir.ronin.generators.resource.referenceData
import com.projectronin.interop.fhir.ronin.generators.util.generateCodeableConcept
import com.projectronin.interop.fhir.ronin.generators.util.generateEffectiveDateTime
import com.projectronin.interop.fhir.ronin.generators.util.generateReference
import com.projectronin.interop.fhir.ronin.generators.util.rcdmMeta
import com.projectronin.interop.rcdm.common.enums.RoninProfile
import com.projectronin.interop.rcdm.common.metadata.ValueSetMetadata
import com.projectronin.interop.rcdm.registry.model.ValueSetList

/**
 * Helps generate ronin body surface area observation profile, applies meta and randomly generates an
 * acceptable code from the [possibleBodySurfaceAreaCodes] list, category is generated by base-vital-signs
 */
fun rcdmObservationBodySurfaceArea(
    tenant: String,
    block: ObservationGenerator.() -> Unit,
): Observation {
    return rcdmBaseObservation(tenant) {
        block.invoke(this)
        meta of rcdmMeta(RoninProfile.OBSERVATION_BODY_SURFACE_AREA, tenant) {}
        category of listOf(codeableConcept { coding of vitalSignsCategory })
        code of generateCodeableConcept(code.generate(), possibleBodySurfaceAreaCodes.codes.random())
        subject of generateReference(subject.generate(), subjectReferenceOptions, tenant, "Patient")
        effective of generateEffectiveDateTime(effective.generate(), possibleDateTime)
    }
}

fun Patient.rcdmObservationBodySurfaceArea(block: ObservationGenerator.() -> Unit): Observation {
    val data = this.referenceData()
    return rcdmObservationBodySurfaceArea(data.tenantId) {
        block.invoke(this)
        subject of
            generateReference(
                subject.generate(),
                subjectReferenceOptions,
                data.tenantId,
                "Patient",
                data.udpId,
            )
    }
}

val possibleBodySurfaceAreaCodes =
    ValueSetList(
        listOf(
            Pair("8277-6", "Body surface area"),
            Pair("3140-1", "Body surface area Derived from formula"),
            Pair("3139-3", "Body surface area Measured"),
        ).map {
            coding {
                system of loinc
                version of "2.74"
                code of it.first
                display of it.second
            }
        },
        ValueSetMetadata(
            registryEntryType = "value_set",
            valueSetName = "bodysurfaceareabsa",
            valueSetUuid = "45354da4-30b4-433e-b5aa-d99a903d5dc9",
            version = "3",
        ),
    )
